"""Update degradation schema for phase 4 calibration

Revision ID: 0bdd08c2f252
Revises: 771003bf8804
Create Date: 2026-02-22 09:26:36.239646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bdd08c2f252'
down_revision: Union[str, Sequence[str], None] = '771003bf8804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('degradation_models', sa.Column('season', sa.Integer(), nullable=False))
    op.add_column('degradation_models', sa.Column('track_id', sa.String(), nullable=False))
    op.add_column('degradation_models', sa.Column('alpha', sa.Float(), nullable=False))
    op.add_column('degradation_models', sa.Column('base_wear_rate', sa.Float(), nullable=False))
    op.add_column('degradation_models', sa.Column('cliff_threshold', sa.Float(), nullable=False))
    op.add_column('degradation_models', sa.Column('beta', sa.Float(), nullable=False))
    op.add_column('degradation_models', sa.Column('gamma', sa.Float(), nullable=False))
    op.add_column('degradation_models', sa.Column('fuel_per_km', sa.Float(), nullable=False))
    op.add_column('degradation_models', sa.Column('fuel_time_penalty_per_kg', sa.Float(), nullable=False))
    op.add_column('degradation_models', sa.Column('rmse_score', sa.Float(), nullable=False))
    op.add_column('degradation_models', sa.Column('mae_score', sa.Float(), nullable=False))
    op.add_column('degradation_models', sa.Column('sample_count', sa.Integer(), nullable=False))
    op.add_column('degradation_models', sa.Column('calibration_timestamp', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_deg_models_race_driver_compound'), table_name='degradation_models')
    op.create_index('ix_deg_models_season_track_compound', 'degradation_models', ['season', 'track_id', 'compound'], unique=True)
    op.drop_constraint(op.f('degradation_models_driver_id_fkey'), 'degradation_models', type_='foreignkey')
    op.drop_constraint(op.f('degradation_models_race_id_fkey'), 'degradation_models', type_='foreignkey')
    op.drop_column('degradation_models', 'model_type')
    op.drop_column('degradation_models', 'driver_id')
    op.drop_column('degradation_models', 'cliff_lap_estimate')
    op.drop_column('degradation_models', 'coefficient_primary')
    op.drop_column('degradation_models', 'race_id')
    op.drop_column('degradation_models', 'coefficient_secondary')
    op.drop_column('degradation_models', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('degradation_models', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('degradation_models', sa.Column('coefficient_secondary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('degradation_models', sa.Column('race_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('degradation_models', sa.Column('coefficient_primary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('degradation_models', sa.Column('cliff_lap_estimate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('degradation_models', sa.Column('driver_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('degradation_models', sa.Column('model_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('degradation_models_race_id_fkey'), 'degradation_models', 'races', ['race_id'], ['id'])
    op.create_foreign_key(op.f('degradation_models_driver_id_fkey'), 'degradation_models', 'drivers', ['driver_id'], ['id'])
    op.drop_index('ix_deg_models_season_track_compound', table_name='degradation_models')
    op.create_index(op.f('ix_deg_models_race_driver_compound'), 'degradation_models', ['race_id', 'driver_id', 'compound'], unique=False)
    op.drop_column('degradation_models', 'calibration_timestamp')
    op.drop_column('degradation_models', 'sample_count')
    op.drop_column('degradation_models', 'mae_score')
    op.drop_column('degradation_models', 'rmse_score')
    op.drop_column('degradation_models', 'fuel_time_penalty_per_kg')
    op.drop_column('degradation_models', 'fuel_per_km')
    op.drop_column('degradation_models', 'gamma')
    op.drop_column('degradation_models', 'beta')
    op.drop_column('degradation_models', 'cliff_threshold')
    op.drop_column('degradation_models', 'base_wear_rate')
    op.drop_column('degradation_models', 'alpha')
    op.drop_column('degradation_models', 'track_id')
    op.drop_column('degradation_models', 'season')
    # ### end Alembic commands ###
