"""Add Idempotent Unique Constraints and denormalize Lap

Revision ID: 771003bf8804
Revises: 8eadadf836d0
Create Date: 2026-02-22 08:38:00.086588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771003bf8804'
down_revision: Union[str, Sequence[str], None] = '8eadadf836d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drivers_code_season'), table_name='drivers')
    op.create_index('ix_drivers_code_season', 'drivers', ['driver_code', 'season'], unique=True)
    op.add_column('laps', sa.Column('race_id', sa.UUID(), nullable=False))
    op.add_column('laps', sa.Column('driver_id', sa.UUID(), nullable=False))
    op.create_index('ix_laps_race_driver_lap', 'laps', ['race_id', 'driver_id', 'lap_number'], unique=True)
    op.create_foreign_key(None, 'laps', 'races', ['race_id'], ['id'])
    op.create_foreign_key(None, 'laps', 'drivers', ['driver_id'], ['id'])
    op.drop_index(op.f('ix_races_season_grand_prix'), table_name='races')
    op.create_index('ix_races_season_grand_prix', 'races', ['season', 'grand_prix'], unique=True)
    op.create_index('ix_stints_race_driver_start', 'stints', ['race_id', 'driver_id', 'start_lap'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stints_race_driver_start', table_name='stints')
    op.drop_index('ix_races_season_grand_prix', table_name='races')
    op.create_index(op.f('ix_races_season_grand_prix'), 'races', ['season', 'grand_prix'], unique=False)
    op.drop_constraint(None, 'laps', type_='foreignkey')
    op.drop_constraint(None, 'laps', type_='foreignkey')
    op.drop_index('ix_laps_race_driver_lap', table_name='laps')
    op.drop_column('laps', 'driver_id')
    op.drop_column('laps', 'race_id')
    op.drop_index('ix_drivers_code_season', table_name='drivers')
    op.create_index(op.f('ix_drivers_code_season'), 'drivers', ['driver_code', 'season'], unique=False)
    # ### end Alembic commands ###
