"""Initial schema

Revision ID: 8eadadf836d0
Revises: 
Create Date: 2026-02-22 08:26:48.701651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eadadf836d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_code', sa.String(length=3), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drivers_code_season', 'drivers', ['driver_code', 'season'], unique=False)
    op.create_table('races',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('grand_prix', sa.String(), nullable=False),
    sa.Column('circuit', sa.String(), nullable=False),
    sa.Column('circuit_length_km', sa.Float(), nullable=False),
    sa.Column('total_laps', sa.Integer(), nullable=False),
    sa.Column('race_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_races_season_grand_prix', 'races', ['season', 'grand_prix'], unique=False)
    op.create_table('degradation_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('race_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('compound', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('coefficient_primary', sa.Float(), nullable=False),
    sa.Column('coefficient_secondary', sa.Float(), nullable=True),
    sa.Column('r_squared', sa.Float(), nullable=False),
    sa.Column('cliff_lap_estimate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deg_models_race_driver_compound', 'degradation_models', ['race_id', 'driver_id', 'compound'], unique=False)
    op.create_table('stints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('race_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('compound', sa.String(), nullable=False),
    sa.Column('start_lap', sa.Integer(), nullable=False),
    sa.Column('end_lap', sa.Integer(), nullable=False),
    sa.Column('stint_length', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stints_compound', 'stints', ['compound'], unique=False)
    op.create_index('ix_stints_driver_id', 'stints', ['driver_id'], unique=False)
    op.create_index('ix_stints_race_id', 'stints', ['race_id'], unique=False)
    op.create_table('laps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stint_id', sa.UUID(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_time_seconds', sa.Float(), nullable=True),
    sa.Column('sector_1_seconds', sa.Float(), nullable=True),
    sa.Column('sector_2_seconds', sa.Float(), nullable=True),
    sa.Column('sector_3_seconds', sa.Float(), nullable=True),
    sa.Column('track_status', sa.String(), nullable=True),
    sa.Column('is_green_flag', sa.Boolean(), nullable=False),
    sa.Column('fuel_estimate_kg', sa.Float(), nullable=True),
    sa.Column('telemetry_file_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stint_id'], ['stints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_laps_lap_number', 'laps', ['lap_number'], unique=False)
    op.create_index('ix_laps_stint_id', 'laps', ['stint_id'], unique=False)
    op.create_table('micro_sectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lap_id', sa.UUID(), nullable=False),
    sa.Column('corner_number', sa.Integer(), nullable=False),
    sa.Column('entry_speed_kmh', sa.Float(), nullable=True),
    sa.Column('apex_speed_kmh', sa.Float(), nullable=True),
    sa.Column('exit_speed_kmh', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('micro_sectors')
    op.drop_index('ix_laps_stint_id', table_name='laps')
    op.drop_index('ix_laps_lap_number', table_name='laps')
    op.drop_table('laps')
    op.drop_index('ix_stints_race_id', table_name='stints')
    op.drop_index('ix_stints_driver_id', table_name='stints')
    op.drop_index('ix_stints_compound', table_name='stints')
    op.drop_table('stints')
    op.drop_index('ix_deg_models_race_driver_compound', table_name='degradation_models')
    op.drop_table('degradation_models')
    op.drop_index('ix_races_season_grand_prix', table_name='races')
    op.drop_table('races')
    op.drop_index('ix_drivers_code_season', table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
